### ISSUE TITLE
Type css:StyleSheet not found in xmlns clr-namespace:XamlCSS;assembly=XamlCSS

### ISSUE THREAD

**Issue by JohnLouderback** [warappa/XamlCSS#63]
I'm trying to use this in my Xamarin Forms project, but I'm encountering this exception when the app launches (on iOS) `Type css:StyleSheet not found in xmlns clr-namespace:XamlCSS;assembly=XamlCSS`

Here is an excerpt of where I'm using this in my XAML:

```xaml
<?xml version="1.0" encoding="utf-8"?>

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Radi.Views"
             xmlns:xfGloss="clr-namespace:XFGloss;assembly=XFGloss"
             xmlns:xlabs="clr-namespace:XLabs.Forms.Controls;assembly=XLabs.Forms"
             xmlns:customControls="clr-namespace:Radi.CustomControls"
             xmlns:viewModels="clr-namespace:Radi.ViewModels;assembly=Radi.iOS"
             xmlns:css="clr-namespace:XamlCSS;assembly=XamlCSS"
             xmlns:cssXF="clr-namespace:XamlCSS.XamarinForms;assembly=XamlCSS.XamarinForms"
             x:Class="Radi.Views.RegistrationPage">
  <ContentPage.BindingContext>
    <viewModels:RegistrationPageViewModel />
  </ContentPage.BindingContext>

  <ContentPage.Resources>
    <ResourceDictionary>
      <css:StyleSheet x:Key="LocalStyle">
        <css:StyleSheet.Content>
          Label {
            TextColor: Red;
          }
        </css:StyleSheet.Content>
      </css:StyleSheet>
    </ResourceDictionary>
  </ContentPage.Resources>
```
If it's of any consequence, it's a "Shared" project rather than PCL

**Comment by warappa** [comment]
I have no Apple device but I created a new shared Xamarin.Forms project and copied the xml-namespace declarations and your ResourceDictionary into it, and applied the stylesheet to the contentpage with a DynamicResource - it worked here.

I cannot say if the error you're encountering is due to iOS or something else.

Checklist:
- XamlCSS *and* XamlCSS.XamarinForms on iOS project installed?
- Release or Debug build?
- Have you initialized XamlCSS in App constructor with `XamlCSS.XamarinForms.Css.Initialized(this)` where `this` is your _Xamarin-Forms_ App-class?
- Maybe XamlCSS gets removed by the link-optimization - can you just create a new instance of XamlCSS.StyleSheet in your App constructor just to ensure it is not removed?

**Comment by JohnLouderback** [comment]
Oops! I didn't notice the `Css.Initialize` method call in the App constructor when I was looking at the example. That fixed it! Thanks!
